### ISSUE TITLE
Disable log output

### ISSUE THREAD

**Issue by Glifery** [wormling/phparia#1]
When I run example code of listening for ARI events, I get some log messages in my console or web browser like this:

> 2015-06-04T13:04:29+03:00 NOTICE (5): Request object created!
> 2015-06-04T13:04:29+03:00 NOTICE (5): Handshake received!
> ...

It seems like Zend Logger put notices directly to default output stream. How can I change this behavior and disable output? I haven't found a way to do it yet. Thank you

**Comment by wormling** [comment]
Line 151 of phparia\Client\Client.php
$this->logWriter = new \Zend\Log\Writer\Stream("php://output");

That is the cause.  I actually don't really want to even use zend logger and plan to allow optional injected PSR-3.  I may have time after work tomorrow to make a change if you have a suggestion.  I was thinking a yml file with config, or just making a logger optional in general.

**Comment by wormling** [comment]
Oh, if you have an idea, go ahead and modify that file and submit a pull request.

**Comment by Glifery** [comment]
Thank you for your answer.
I think the best solution is to replace output stream definition from Client to something like config. But for now it would be enough if we could just turn it off. It's important for my application cause I want return a result of ARI handler in JSON format and I need clean output stream.

**Comment by wormling** [comment]
I have suppressed the logger for now.  I'll add optional PSR-3 when I get time.
