### ISSUE TITLE
Listen all events

### ISSUE THREAD

**Issue by hartois** [wormling/phparia#20]
Hello,
I want forward all ARI events into ZMQ queue.
How can I catch all events?

**Comment by wormling** [comment]
I added an example [here](https://github.com/wormling/phparia/blob/master/src/wormling/phparia/Examples/EventsExample.php).

Refer to the AriClient.php and AmiClient.php for more information on how that works.

**Comment by kerstvo** [comment]
It triggers me `Call to a member function on() on null`

at this line https://github.com/wormling/phparia/blob/master/src/wormling/phparia/Examples/EventsExample.php#L73
