### ISSUE TITLE
Wrong name of event ChannelStateChanged

### ISSUE THREAD

**Issue by vU97N** [wormling/phparia#22]
Hi,
I found wrong name of event ChannelStateChange**d** which should be ChannelStateChange (without "d" at the end) in Events/Event.php. See [here](https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+REST+Data+Models#Asterisk12RESTDataModels-ChannelStateChange).

`class Event extends Message implements EventInterface
{
...
    const CHANNEL_STATE_CHANGED = 'ChannelStateChanged';
...

`

**Comment by wormling** [comment]
Thanks!
