### ISSUE TITLE
Missing constant for ChannelDialplan event

### ISSUE THREAD

**Issue by vU97N** [wormling/phparia#25]
Hi,
in the Event class is not defined constant for _ChannelDialplan_ event,
so I added it there and added methods Channel::onChannelDialplan() and Channel::onceChannelDialplan().
[patch2.zip](https://github.com/wormling/phparia/files/1118714/patch2.zip)

**Comment by wormling** [comment]
Thanks for you contribution!  For faster updates in the future please submit code as a pull request.
