### ISSUE TITLE
Cannot unpack array with string keys

### ISSUE THREAD

**Issue by byphone** [wormling/phparia#30]
Hello, 

I try with the code below :
```
        $ariAddress = 'ws://10.67.0.113:8088/ari/events?api_key=svix:svix&app=hello-world';
        $logger = new \Zend\Log\Logger();
        $logWriter = new \Zend\Log\Writer\Stream("php://output");
        $logger->addWriter($logWriter);
        $filter = new \Zend\Log\Filter\Priority(\Zend\Log\Logger::NOTICE);
        $logWriter->addFilter($filter);


        $this->client = new \phparia\Client\Phparia($logger);
        $this->client->connect($ariAddress);
        $this->client->onStasisStart(function(StasisStart $event) {

        });
        $this->client->run();
```
I get a fatal error : "Cannot unpack array with string keys"
in file EventEmitterTrait.php on line 117

Any help ?

**Comment by byphone** [comment]
Perhaps evenement/evenement package version
i think we have to use 2.1.0 and not dev-master

**Comment by wormling** [comment]
Looks like https://stackoverflow.com/questions/40663687/cannot-unpack-array-with-string-keys since it seems to be the ... operator causing this.  I will update the composer.json and lock file with the correct version range.
