### ISSUE TITLE
Fatal error: Uncaught exception 'Pest_Forbidden' with message '{"message":"Write access denied"}' 

### ISSUE THREAD

**Issue by shankar667** [wormling/phparia#4]
I'm getting the following error, can you help on this issue?

Fatal error: Uncaught exception 'Pest_Forbidden' with message '{"message":"Write access denied"}'

**Comment by wormling** [comment]
Can you post a stack trace?

**Comment by shankar667** [comment]
Thank you for quick reply Brian!!

I updated read_only = no in "ari.conf" works perfect, thank you so much.
